# Generated by Django 3.2.8 on 2023-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
